shared:
    image: node:6
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - install: npm install
            - validate: ./node_modules/.bin/template-validate
    publish:
        requires: [main]
        steps:
            - install: npm install
            - publish: ./node_modules/.bin/template-publish
            - tag: ./node_modules/.bin/template-tag --name dummy_template --version 1.3.0 --tag first
    detached-template-remove:
        steps:
            - install: npm install
            # For next pass, remove the `-n` flag
            # A pipeline should be able to publish multiple templates, hence name specification
            - remove_template: ./node_modules/.bin/template-remove --name dummy_template
    detached-tag-remove:
        steps:
            - install: npm install
            - remove_tag: ./node_modules/.bin/template-remove-tag --name dummy_template --tag first
