shared:
    image: node:6
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - install: npm install screwdriver-template-main
            - validate: ./node_modules/.bin/template-validate
        environment:
            SD_TEMPLATE_PATH: ./sd-template.yaml
    publish:
        requires: [main]
        steps:
            - install: npm install screwdriver-template-main
            - publish: ./node_modules/.bin/template-publish
        environment:
            SD_TEMPLATE_PATH: ./sd-template.yaml
    detached-remove:
        steps:
            - install: npm install
            - remove: ./remove.js -n dummy_template
